name: Run every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *' #run every 5 minutes https://crontab.guru/#*/5_*_*_*_*

jobs:
  cron:
    name: Run every 5 minutes
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "Hello World"
